FleetManagementSystem/FleetManagementSystem.MVCClient/Controllers/DispatchController.cs
using FleetManagementSystem.MVCClient.Models;
using FleetManagementSystem.MVCClient.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using domain = FleetManagementSystem.Domain;

namespace FleetManagementSystem.MVCClient.Controllers
{
    public class DispatchController : Controller
    {
        private domain.DomainHelper dh = new domain.DomainHelper();
        // GET: Dispatch
        public ActionResult Index()
        {
            return View("Index","_Layout");
        }

        public ActionResult DriversList()
        {
            var driverList = dh.GetDriverList();
            var drivers = ClientHelper.GetDriverList(driverList);
            return View("DriversList","_Layout",drivers);
        }

        public ActionResult DriverAssignment(int id)
        {
            var driverList = dh.GetDriverList();
            var drivers = ClientHelper.GetDriverList(driverList);
            var driver = drivers.FirstOrDefault(d => d.Id == id);

            var aList = dh.GetAssignList();
            var assignments = ClientHelper.GetAssignmentList(aList);

            var assignment = assignments.FirstOrDefault(a => a.driverId == driver.Id);
            var daList = new List<ViewModels.DriverAssignment>();
            foreach(var item in assignments)
            {
                if(item.driverId == driver.Id)
                {
                    daList.Add(item);
                }
            }
            
            return View("DriverAssignment", "_Layout",daList);
        }

        public ActionResult MapRouter(int id)
        {
            var aList = dh.GetAssignList();
            var assignments = ClientHelper.GetAssignmentList(aList);

            var assignment = assignments.FirstOrDefault(a => a.aId == id);
            return View("MapRouter", "_Layout", assignment);
        }

        public ActionResult AddAssignment(int id)
        {
            var driverList = dh.GetDriverList();
            var drivers = ClientHelper.GetDriverList(driverList);
            var driver = drivers.FirstOrDefault(d => d.Id == id);

            var aList = dh.GetAssignList();
            var assignments = ClientHelper.GetAssignmentList(aList);
            var assignment = assignments.FirstOrDefault(a => a.driverId == driver.Id);

            return View("AddAssignment", "_Layout",assignment);
        }

        [HttpPost]
        public ActionResult AddAssignment(DriverAssignment adm)
        {
            var s = adm.sAddressProp;
            var e = adm.eAddressProp;
            s = s.Replace(" ", "-");
            e = e.Replace(" ", "-");
            try
            {
                if(ModelState.IsValid)
                {
                    string c = adm.completeProp;
                    int co = 0;

                    if (c == "Yes" || c == "yes")
                    {
                        co = 1;
                    }

                    var a = new domain.AssignmentDTO()
                    {
                        driverId = adm.driverId,
                        sAddress = s,
                        eAddress = e,
                        details = adm.detailsProp,
                        complete = co
                    };
                    if(dh.AddAssignment(a))
                    {
                        Console.WriteLine(adm.driverId);
                        return View("Index", "_Layout");
                    }
                }
                throw new Exception();
            }
            catch
            {
                return View("Index", "_Layout");
            }
        }
    }
}

FleetManagementSystem/FleetManagementSystem.MVCClient/Controllers/HomeController.cs
using FleetManagementSystem.MVCClient.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using domain = FleetManagementSystem.Domain;

namespace FleetManagementSystem.MVCClient.Controllers
{
    public class HomeController : Controller
    {

        private domain.DomainHelper dh = new domain.DomainHelper();

        // GET: Home
        public ActionResult Index()
        {
            Drivr d = new Drivr();
            return View("Index","_Layout2", d);
        }

        public ActionResult Login(Drivr d)
        {
            var e = new domain.DriverDTO()
            {
                Id = d.Id,
                handle = d.handleProp,
                pass = d.passProp
            };
            if (dh.login(e))
            {
                return RedirectToAction("Assignment", "Driver",e);
            }
            else
            {
                TempData["alert"] = "Login Failed!";
                return View("Login", "_Layout2", d);
            }
        }

        public ActionResult LoginInit()
        {
            var e = new Drivr();

            return View("Login", "_Layout2", e);
        }
    }
}

FleetManagementSystem/FleetManagementSystem.MVCClient/Views/Home/Index.cshtml
@model FleetManagementSystem.MVCClient.ViewModels.Drivr

@{
    ViewBag.Title = "index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Fleet Management</title>
</head>

<body>
    <div>
        <h1>Welcome to American Fleet Management</h1> 
    </div>
    <div>
        <h3>Please select your role</h3>
        @*<input type="button" value="Some text" onclick="window.location.href='<%= Url.Action(" actionName", "controllerName" ) %>';" />*@
        <input type="button" value="Dispatcher" onclick= "@("window.location.href='" + @Url.Action("Index", "Dispatch" ) + "'") ;" />
        <input type="button" value="Driver" onclick="@("window.location.href='" + @Url.Action("LoginInit", "Home" ) + "'") ;" />
    </div>

    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>

FleetManagementSystem/FleetManagementSystem.MVCClient/Views/Home/Login.cshtml
@model FleetManagementSystem.MVCClient.ViewModels.Drivr

@{
    ViewBag.Title = "Login";
}

<div>
     <h1>Welcome to American Fleet Management</h1>
</div>
    <div>
        <h3>Please select your role</h3>
        @* <input type="button" value="Some text" onclick="window.location.href='<%= Url.Action(" actionName", "controllerName" ) %>';" />*@
        <input type="button" value="Dispatcher" onclick="@("window.location.href='" + @Url.Action("Index", "Dispatch" ) + "'") ;" />
        <input type="button" value="Driver" onclick="@("window.location.href='" + @Url.Action("LoginInit", "Home" ) + "'") ;" />
    </div>
    <h2>Login</h2>

@if (TempData["alert"] != null)
{
    <p>@TempData["alert"]</p>
}

    @using (Html.BeginForm("Login", "Home", FormMethod.Get))
    {
        <div class="form-group">
           @Html.LabelFor(m => Model.handle, new { @class = "control-label" })
           @Html.EditorFor(m => Model.handleProp, new { id = Model.handleProp, htmlAttributes = new { @class = "form-control", @placeholder = "User Name", } })

           @Html.LabelFor(m => Model.pass, new { @class = "control-label" })
           @Html.EditorFor(m => Model.passProp, new { id = Model.passProp, htmlAttributes = new { @type = "password", @class = "form-control", @placeholder = "Password", } })
        </div>
        <input type="submit" value="Login" />
     }